### ISSUE TITLE
Some interlaced videos play choppily on the Jellyfin Roku client (sample provided)

### ISSUE THREAD

**Issue by nothing2obvi** [jellyfin/jellyfin-roku#557]
### This issue respects the following points:

- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin-roku/issues?q=is%3Aissue) _(I've searched open and closed issues)_.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Jellyfin Server Version

10.10.7

### Roku Client Version

3.0.10

### Bug Description

(Please see Additional Context for sample)

The issue occurs inconsistently — certain 1080i titles exhibit noticeably uneven or stuttered motion, while others play smoothly.

Playback of the same files on Android TV and the Jellyfin Web client is smooth, suggesting the issue is Roku-specific.

Selecting “Force Transcode (Remux Disabled)” does not resolve the problem; the server still reports the file as direct playing.

Example Info:

Video
Codec: H264 (MPEG-4 AVC)
Profile: High @ Level 4.1
Resolution: 1920×1080 (1080i)
Framerate: 29.970 fps (interlaced)
Bitrate: 5548 kbps
Bit depth: 8-bit
Pixel format: yuv420p
Aspect ratio: 16:9
Reference frames: 1

Audio
Codec: FLAC
Channels: 2.0 (stereo)
Language: Japanese
Sample rate: 48 kHz
Bitrate: 2304 kbps
Bit depth: 24-bit

### Steps to Reproduce

1. Open the Jellyfin Roku app.
2. Play an interlaced 1080i video (see example below).
3. Observe that motion appears choppy or uneven compared to playback on Android TV or Web.
4. Attempt to enable Force Transcode (Remux Disabled) — note that playback remains direct play and choppiness persists.

### Expected Behavior

Interlaced content (e.g., 1080i H.264) should play back smoothly and consistently on Roku, matching performance on Android TV and the Web client.

If the device cannot handle interlaced direct play efficiently, the client should fall back to transcoding when “Force Transcode” is selected.

### Is the server local or remote?

local

### Is the server connection HTTP or HTTPS?

http

### Additional Context

https://share.thehouses.xyz/s/xIRvHBKC

**Comment by cewert** [comment]
sample file link doesn't work

**Comment by nothing2obvi** [comment]
Hi @cewert, it's alright. It seems to have resolved when the bitrate limit is enabled.

If you still want to explore this, the share link should work now. Otherwise, I think it's okay to close this. Thanks for your time.

**Comment by cewert** [comment]
> It seems to have resolved when the bitrate limit is enabled.

Did bitrate limit force a transcode? Sounds like you're still having problems direct playing the file.

**Comment by nothing2obvi** [comment]
Yes, it did force a transcode, actually.
