### ISSUE TITLE
Unable to seek past 1 minute when transcoding (EDITED)

### ISSUE THREAD

**Issue by Rand0mB0y** [jellyfin/jellyfin-roku#582]
I've added the word `(EDITED)` or `UPDATE` next to anything different I've found out after more investigation, and since the last update to JF client v3.0.13 and Roku OS v15.
  
### This issue respects the following points:
- [x] This issue is **not** already reported on [GitHub](https://github.com/jellyfin/jellyfin-roku/issues?q=is%3Aissue) _(I've searched open and closed issues)_.
- [x] I agree to follow Jellyfin's [Code of Conduct](https://jellyfin.org/docs/general/community-standards.html#code-of-conduct).
- [x] This report addresses only a single issue; If you encounter multiple issues, kindly create separate reports for each one.

### Jellyfin Server Version
10.11.2 / 10.11.3 / 10.11.4 (but it was happening already with 10.10 if I remember correctly) (EDITED)

### Roku Client Version
3.0.11 / 3.0.13 (but it was happening already with 3.0.10) (EDITED)

### Bug Description

When transcoding, I'm unable to skip forward if I want to reach anything further than minute 1:00 (roughly). The player will force the playback to 1:00 no matter what.  
The video still plays correctly.... but say that you are at minute 14:00, and you want to go back just a few seconds to rewatch a small part that you missed, so you press the back arrow? Well, as soon as you press the button it will go back to minute 1:00 (roughly) and there is no way to go forward to minute 14:00 unless pressing play and wait*.
  

**UPDATE (2025-12-06):**
*QUIRK: In my case, with these problematic files, the "instant replay" button seems to go back a few seconds without issues. This is at least something, if you just wanna rewind a little bit.

<img width="343" alt="Image" src="https://github.com/user-attachments/assets/9ffb8ea4-ab80-48c0-abdb-527e1be7a222"/>
</br></br>

**UPDATE (2025-12-06):**
Since updating to the latest release v3.0.13, the behaviour seems to have changed slightly. If I play a video that requires audio-only transcoding, this gets reported as "Direct Play" in the Jellyfin admin dashboard. But the file is still transcoding, and the issue is still occurring (while transcoding). I could easily figure out that the file is transcoding because I have HW acceleration is enabled, and I could see the GPU percentage going up while playing the video, besides, the log and the transcode folders confirms this. So the issue still is regarding transcoded files only, even though the admin dashboard may lie to you!
  

**UPDATE (2025-12-06):**
Since updating to the latest release v3.0.13, I could re-enable the option to burn subtitles into the transcoded video thanks to the #591 fix. As soon as I re-enabled this (Settings → Playback → Burn in subtitles when transcoding → Enabled), many of my videos were fixed... somehow! Sadly, not all of them. I am adding this info, because between this and the previous quirk, you may at least get by for a bit, depending on your library... and because hopefully all these extra info can help the devs to understand what's causing this.

**UPDATE (2025-12-06):**
If you rename the folder containing the problematic video (or the video name itself), then it seems to play fine, but you'll lose watched status, favourite, collections and all manual metadata. All you need to do is to add a space or any character to the folder, and then launch a Jellyfin scan. Now it plays fine. But this may revert to not working behaviour if you run a "replace all metadata" scan in the future.
This, also, mean that any newly added files may not be "problematic" which makes this difficult to debug, I'd imagine.
  

### Steps to Reproduce

1. Start playing a video that requires audio transcoding
2. Press arrow to skip forward and try to reach minute 5:00
OR
1. Start playing a media that requires transcoding
2. Play till minute 5:00
3. Now try to go back to minute 4:50 using the D pad arrow left button
**IMPORTANT: ** If you can't replicate, try to run a "replace all metadata" scan (EDITED)
  
### Expected Behavior
You should be able to seek... to move forward and backward in time past one minute from the seek bar.

### Is the server local or remote?
local

### Is the server connection HTTP or HTTPS?
http

**Comment by jimdogx** [comment]
I'm sorry, but I'm not quite understanding.  Whenever I use the remote it lets me seek forward and backward by 10 seconds at a time.  Which button exactly are you pressing?  Is the video paused when you press it?  Or while it's playing?  I've tried several different ways and it always lets me go back/forward by 10 seconds (not 1 minute).

**Comment by Rand0mB0y** [comment]
> I'm sorry, but I'm not quite understanding. Whenever I use the remote it lets me seek forward and backward by 10 seconds at a time. Which button exactly are you pressing? Is the video paused when you press it? Or while it's playing? I've tried several different ways and it always lets me go back/forward by 10 seconds (not 1 minute).

It's the whole seeking feature that it's broken when transcoding. I'm unable to seek forward past minute 1:00 for whatever reason. It's not allowing me to jump, for instance, to minute 8:00 when streaming a transcoded file. Even if I wait a little bit I cannot still seek past minute one (it's not precisely 1:00 sometimes it can reach minute 1:12 for instance, but I can never jump to minute 2:00). 
If I let the video go without seeking and the play time reaches minute 8:45 for instance, and then I press the forward button (or right arrow) then it goes back to minute 1:00. And the same issue happens if I seek backward.
I hope it makes sense.

**Comment by jimdogx** [comment]
Sorry, I'm an idiot, your title does say when transcoding... I was direct playing.  I'll retest 👍

**Comment by jimdogx** [comment]
So most (if not all) of my stuff direct plays.  But I forced transcoding with both a bitrate limit as well as the "force transcoding" option on the app.  I'm able to fast forward as far as I want.

Any chance this is a server issue (underpowered)?  Is this a LiveTV recording by chance?

**Comment by Rand0mB0y** [comment]
> So most (if not all) of my stuff direct plays. But I forced transcoding with both a bitrate limit as well as the "force transcoding" option on the app. I'm able to fast forward as far as I want.
> 
> Any chance this is a server issue (underpowered)? Is this a LiveTV recording by chance?

Nope not live TV. And the server doesn't seem to run under stress with a 4% CPU and 60% RAM max usage while transcoding.
I should specify that almost all my transcoding happens due to audio codec only incompatibility, with the video being directly streamed.
Therefore, perhaps in order to reproduce the issue, a video with a 5.1 AC3 or DTS track is needed.

**Comment by Rand0mB0y** [comment]
@jimdogx I have done some more testing and I figured that when a newly added media needs transcoding, then the seeking feature works as it should. Instead, the issue seems to occur only when the item that need transcoding was already present in the catalogue before migrating to 10.11.x.
Even if I simply rename one of the "problematic" media file and allow Jellyfin to rescan, then I am able to seek fast/backward. The same file, no remux, no encode, if I just simply add a space to its name then I can skip back/forward just fine.
  
Some other (hopefully useful) info I figured:
- When seek feature is broken, subtitles fail to appear
- When seek feature is broken, the skip forward/backwards moves in increments of 2 seconds instead of 10 seconds

**Comment by jimdogx** [comment]
🤔  .... interesting.  I haven't upgraded to 10.11 yet (I probably should), but this sounds like a server issue.  I'll have to check with the server team to see what they think.

**Comment by brianpardy** [comment]
> Instead, the issue seems to occur only when the item that need transcoding was already present in the catalogue before migrating to 10.11.x.
> Even if I simply rename one of the "problematic" media file and allow Jellyfin to rescan, then I am able to seek fast/backward. The same file, no remux, no encode, if I just simply add a space to its name then I can skip back/forward just fine.

Have you tried running a "replace all metadata" refresh scan on a file that gives you this problem?

I had a problem where chapter images were not displayed in the server app that was fixed by doing so and maybe it will help this issue too. If it helps you can do the same for your entire library.

**Comment by Rand0mB0y** [comment]
@brianpardy @jimdogx 
I've done even more testing, and things are more complicated than I thought.
  
> Have you tried running a "replace all metadata" refresh scan on a file that gives you this problem?

Yes, I tried this. It does not fix the issue. Actually, it made things slightly worse. The "replace all metadata" scan seems to have broken the seeking functionality (while transcoding) of the few files that were actually working before. At the same time, it did not fix the "problematic" files.
  
The only way I am able to make the seeking function work is to run a simple media scan task after renaming the file, or the folder in which the file is contained (even changing the case of a few letters seems to be enough).
But then any future "replace all metadata" scan will revert it back to not working.
  
> ...when a newly added media needs transcoding, then the seeking feature works as it should. Instead, the issue seems to occur only when the item that need transcoding was already present in the catalogue before migrating to 10.11.x.

At this point, I am not 100% sure the issue is related to the 10.11 migration, or it's just the way 10.11 is currently working in general (or something else?).

Also, subtitles seem to never show up when transcoding, whether the seeking function is working or not. Tested srt and ass. I wonder if I should open a separate issue for this?

**Comment by Rand0mB0y** [comment]
> So most (if not all) of my stuff direct plays.

@jimdogx May I ask what is your strategy to avoid transcoding (almost) entirely? Do you encode all your files with the Roku's codec limitations in mind, or is there some Roku settings I may be missing?

**Comment by jimdogx** [comment]
Almost all mkv with either H264 or H265 (hevc).  I'm not saying I don't have anything that transcodes (I'm sure I do somewhere), I'd just have to search through the library to find one 🙃

**Comment by Rand0mB0y** [comment]
> Almost all mkv with either H264 or H265 (hevc). I'm not saying I don't have anything that transcodes (I'm sure I do somewhere), I'd just have to search through the library to find one 🙃

Sorry for double-checking this, but what about audio tracks? Would you feel like confirming that any AC3 audio track should cause audio-only transcoding, or am I doing something wrong? In my system, even if a file has got a single AC3 2.0 audio track, then I get audio-only transcoding.

EDIT: My model is the Roku 4K

**Comment by jimdogx** [comment]
I have a Roku TV connected to a soundbar that can decode Dolby Atmos, DTS, etc.  2.0, 5.1 etc direct plays for me.

**Comment by jimdogx** [comment]
p.s. you mentioned an issue with subtitles, note that a few folks are currently having issues with subtitles (it seems hit or miss right now): See #537 and others.

**Comment by Rand0mB0y** [comment]
> I have a Roku TV connected to a soundbar that can decode Dolby Atmos, DTS, etc. 2.0, 5.1 etc direct plays for me.

Thanks, for clarifying this. It looks like yours is a pretty different setup from mine then.

> p.s. you mentioned an issue with subtitles, note that a few folks are currently having issues with subtitles (it seems hit or miss right now): See https://github.com/jellyfin/jellyfin-roku/issues/537 and others.

Thank you. In the last client update, the option to avoid burning in subtitles while transcoding was added. If I unflag that, then the subs are back. So just the scrub (seek) feature is broken at the moment when transcoding.

> 🤔 .... interesting. I haven't upgraded to 10.11 yet (I probably should), but this sounds like a server issue. I'll have to check with the server team to see what they think.

@jimdogx Did you have any word from the server team? I have tried the JellyRock client (basically a fork of the Roku legacy client) to further test this out, and the seeking feature is equally broken on that client, too. Which may confirm your hypothesis that the issue is on server side. I've seen quite a few transcoding issues reported in the Jellyfin server's Github... not exactly the same as what I experience. I wonder if I shall report this issue over there, too? I don't wanna clog their pages more than they already are.

**Comment by jimdogx** [comment]
I have not heard back.  But given that it's an issue with multiple (different) Roku clients and you were able to get different outcomes based on filenames and/or metadata, it might be worth a shot heading over to the server Github and adding your issue.  If it is deemed a legit server issue, we can close this one 👍

**Comment by Rand0mB0y** [comment]
> I have not heard back. But given that it's an issue with multiple (different) Roku clients and you were able to get different outcomes based on filenames and/or metadata, it might be worth a shot heading over to the server Github and adding your issue. If it is deemed a legit server issue, we can close this one 👍
  
@jimdogx I updated to 10.11.3 today, tested every client/device I could (official and third party clients on Android, AndroidTV, iOS, Windows), but I am still unable to skip past minute 1 when transcoding on Roku, while it skips fine if transcoding on every other device. 
Because I don't know how much code the two Roku clients share, I think it is still fair to assume that this is likely a client issue.

**Comment by Rand0mB0y** [comment]
Hi I was wondering if there has been any development on this, at all? Am I the only person experiencing this issue? Was anyone able to replicate it? Otherwise, there must be something I am doing wrong on my end.
I am currently using Jellyfin 10.11.4 and the 3.0.13 Roku client, the issues are still the same: 
- I cannot fast forward/backward past one minute and...
- if I am in a middle of a movie and want to go back slightly, it will revert to minute 1:00. 

The second issue is really inconvenient.

**Comment by RavingGrob** [comment]
> Hi I was wondering if there has been any development on this, at all? Am I the only person experiencing this issue? Was anyone able to replicate it? Otherwise, there must be something I am doing wrong on my end.
> I am currently using Jellyfin 10.11.4 and the 3.0.13 Roku client, the issues are still the same: 
> - I cannot fast forward/backward past one minute and...
> - if I am in a middle of a movie and want to go back slightly, it will revert to minute 1:00. 
> 
> The second issue is really inconvenient.

My fiancée just reported having a very similar, if not exact same issue. I'm at work, but I'll do some digging when I get home.

**Comment by RavingGrob** [comment]
> > Hi I was wondering if there has been any development on this, at all? Am I the only person experiencing this issue? Was anyone able to replicate it? Otherwise, there must be something I am doing wrong on my end.
> > I am currently using Jellyfin 10.11.4 and the 3.0.13 Roku client, the issues are still the same: 
> > - I cannot fast forward/backward past one minute and...
> > - if I am in a middle of a movie and want to go back slightly, it will revert to minute 1:00. 
> > 
> > The second issue is really inconvenient.
> 
> My fiancée just reported having a very similar, if not exact same issue. I'm at work, but I'll do some digging when I get home.

So yeah I'm having the exact same problem, though I had completely wiped my database for the .11 update.

For a bit of extra detail I found, it appears that the portion of bar that you can seek through is almost exactly 1% (if my mental math is right) of the total runtime of the media.

**Comment by Rand0mB0y** [comment]
@RavingGrob interesting! I've loaded up a new test server, with the same video files, and I can skip forward/backward fine when streaming from that machine. This is weird, as my second machine has the same server version 10.11.4 and the same Windows 10 OS.
  
A few questions:
1. Do your non-skippable video files contain multi-audio tracks?
2. Which video/audio codecs (aac, ac3, mp3, etc)?
3. How many channels (2.0, 5.1, 7.1, etc)?
4. Which container (mkv, mp4, avi, etc)?
5. Do you play them with subtitles? If so, srt, ass, or what?
6. Are those problematic videos on a Symlink, Hardlink, Junction file path?
7. Is the problem fixed if you rename the folder containing the video, and scan the library (you can just add a space between words)? And does it revert to not working, after a "replace all metadata" rescan?
8. On which OS is your server? Which exact JF server version?
9. Is your problematic file transcoding audio-only, or fully?
  
I'm particularly interested to number 6 and 9.

**Comment by Rand0mB0y** [comment]
I've added more info to the OP, including some quirks that may serve as temporary fixes for most playback scenarios.

**Comment by RavingGrob** [comment]
> @RavingGrob interesting! I've loaded up a new test server, with the same video files, and I can skip forward/backward fine when streaming from that machine. This is weird, as my second machine has the same server version 10.11.4 and the same Windows 10 OS.
>   
> A few questions:
> 1. Do your non-skippable video files contain multi-audio tracks?
> 2. Which video/audio codecs (aac, ac3, mp3, etc)?
> 3. How many channels (2.0, 5.1, 7.1, etc)?
> 4. Which container (mkv, mp4, avi, etc)?
> 5. Do you play them with subtitles? If so, srt, ass, or what?
> 6. Are those problematic videos on a Symlink, Hardlink, Junction file path?
> 7. Is the problem fixed if you rename the folder containing the video, and scan the library (you can just add a space between words)? And does it revert to not working, after a "replace all metadata" rescan?
> 8. On which OS is your server? Which exact JF server version?
> 9. Is your problematic file transcoding audio-only, or fully?
>   
> I'm particularly interested to number 6 and 9.

1. Irrelevant
2. Appears to not matter
3. Tried with forcing stero, all the way to 7.1
4. Most I have is mkv, but I'm sure it happens on MP4 as well
5. Subtitles or no, makes no difference
6. Um, I'm not sure if they're any of that. Just plain on my filesystem.
7. Nope, no change.
8. NixOS Unstable 25.11
9. It's transcoding fully, for tonemapping HDR.

**Comment by Rand0mB0y** [comment]
> 7\. Nope, no change.

Wow that's interesting. That trick fixes any video in my case.
  
Which Jellyfin server version are you running? 10.11.x or previous?

Can you confirm you can't skip properly only when transcoding, though? And that it works fine when direct streaming

**Comment by RavingGrob** [comment]
> > 7\. Nope, no change.
> 
> Wow that's interesting. That trick fixes any video in my case.
>   
> Which Jellyfin server version are you running? 10.11.x or previous?
> 
> Can you confirm you can't skip properly only when transcoding, though? And that it works fine when direct streaming 

10.11.3

I changed a HEVC setting on the Roku, that enabled a movie that originally needed transcoding, to direct play and seeking started working fine. 

But that didn't help any movie that still needed transcoding for HDR etc. So it seems transcoding is definitely the problem.

**Comment by RavingGrob** [comment]
> @RavingGrob interesting! I've loaded up a new test server, with the same video files, and I can skip forward/backward fine when streaming from that machine. This is weird, as my second machine has the same server version 10.11.4 and the same Windows 10 OS.
>   

So, just to confirm, same video files, being the same file paths even, or is this completely different HW? And two servers at the same time, with one not working properly, and one not?

I ask, because I recently deleted my libraryDB to rebuild it because I was having some issues. But I didn't delete everything about the server. I'm suspecting, that somehow there's maybe some conflict how I deleted only some of the old files.

**Comment by jimdogx** [comment]
I'd also be interested in know the difference in HW between the two servers @Rand0mB0y ...  Transcoding happens server side, which could indicate HW that can't handle rewind/fast-forward while transcoding... but in reality may have more to do with something server side such as configs and/or file paths given what you all have discovered so far.

**Comment by Rand0mB0y** [comment]
> So, just to confirm, same video files, being the same file paths even, or is this completely different HW? 

@RavingGrob Completely different hardware. 

> And two servers at the same time, with one not working properly, and one not?

Both server runs at the same time. One working, one not. 
Again,  I wanna stress out the fact that I can make the non working files working, even on the server that's causing the issue, by simply renaming the file folder and rescanning the library. 

> I'd also be interested in know the difference in HW between the two servers @Rand0mB0y ... Transcoding happens server side, which could indicate HW that can't handle rewind/fast-forward while transcoding... but in reality may have more to do with something server side such as configs and/or file paths given what you all have discovered so far.

@jimdogx File paths are structured pretty similarly, on the two servers. But they are different paths, as they do not point to the same media files. I created a testing copy of the files, too. 
The two servers are different, as the test machine is just my laptop. But even the test machine will transcode, but in this case I can skip around.
Anothee difference is that on the test machine I installed 10.11.4 right away, whether my main server was migrated from 10.10.7.
Once again, this 👇

> Again,  I wanna stress out the fact that I can make the non working files working on the server that's causing the issue, by simply renaming the file folder and rescanning the library.

**Comment by RavingGrob** [comment]
This is so weird. Do you have any configuration difference between the servers? Plugins? What HW accel are you using and GPU?

I tried for a second time, nuking the whole JF directory, and upon getting it up and running, still the same issue.

**Comment by Rand0mB0y** [comment]
> Do you have any configuration difference between the servers? Plugins? What HW accel are you using and GPU?

Nope, not the same exact configuration in terms of plugins. The test server has got less stuff going on. 
The main server has got HW acceleration for transcoding while the test server doesn't, **BUT** I set up HW acceleration only recently on the main server (QSV), and unless my memory is playing me tricks, I opened this issue before than that. But I may try playing with that, turning HW acceleration on/off now that you mention it and report.

**Comment by Rand0mB0y** [comment]
@RavingGrob Tested disabling HW accel on main server, and it did not change anything, same issue.

**Comment by RavingGrob** [comment]
> [@RavingGrob](https://github.com/RavingGrob) Tested disabling HW accel on main server, and it did not change anything, same issue.

After a *very* significant amount of my sanity, experimentation, and introspection, I have discovered at least what the culprit in my case, seems to be.

The trickplay images were corrupted, and because resetting the DB didn't help regenerate those, they persisted on each new attempt.

It's likely why when you renamed the files/folder, it fixed it by maybe regenerating the trickplay images?

I have sucessfully fixed an unseekable movie by deleting the trickplay images, and regenerating them.

**Comment by Rand0mB0y** [comment]
@RavingGrob Nice one! 👏👏👏
  
Are you assuming the trickplay images are corrupted because after regenerating the files seeking started to work, or did you also notice something visually strange within the files?
  
Can trickplay be globally set to off on Roku? Does disabling it via settings fix seeking, too? Just to further confirm the culprit. 
  
I will also attempt messing around with this. 

EDIT:
I could not reproduce this. I have tried to delete the trickplay folder (mines are stored within the media folders), but the seek feature was still broken. I did not try to regenerate the tricjplays, though, just delete.
  
I think you may be up to something though, as videos that can't seek, also do not display trickplay thumbnails.
  
Could this possibly be related to this: https://forum.jellyfin.org/t-trickplay-on-roku

**Comment by RavingGrob** [comment]
@Rand0mB0y 

I didn't look more into it, as I'm not sure exactly I'm looking for. 

But what I do know is that at one point, due to how NixOS works, while troubleshooting hw accel a long time ago, I had pinned a part of intel's compute stack's paths (OCL) to ones that weren't permanent, and older than the latest updated ones.

When I reset my Jellyfin server the first time, I also did a "GarbageCollection" which removed the bits that my system were looking at.

Initially, I thought *that* had to be my smoking gun, but media still had the seeking issue after addressing it.

And then I realized that brand new media that i added *after* I fixed that pinning fiasco, worked for seeking.

**Comment by RavingGrob** [comment]
Actually... There's a second layer to this issue 

<img width="1186" height="437" alt="Image" src="https://github.com/user-attachments/assets/aa8aca2c-8bef-4cc3-8c42-9819ecaaa6e8" />

It seems that for my system, some of my movies in particular have *2* .nfo files.

If I delete the more specifically named one, and restart the server (might take multiple attempts?), then that media will seek properly.

Some of my media just needed new trickplay, as I confirmed this with some of my series, that I only deleted the trickplay images, but my older movies have these double .nfo files that are *also* stopping seeking specifically during transcoding.

**Comment by RavingGrob** [comment]
My previous deleted comment was actually a red herring.

I've gone even further. The behaviour of generating trickplay images, appears to have two different logics at play.

If you go into the "Scheduled Tasks" and generate trickplay images, it will use the folder name of the media. In the example path "/Big Hero 6/Big Hero 6 (2014) Blu-ray-2160p.mkv/" "Big Hero 6" will be the name of the trickplay, rather than "Big Hero 6 (2014) Blu-ray-2160p"

However, if you instead go to the individual movie, and refresh the metadata *AND* the trickplay images, that will then be named "Big Hero 6 (2014) Blu-ray-2160p.trickplay

<img width="1019" height="794" alt="Image" src="https://github.com/user-attachments/assets/c8e80b9c-65f3-48f2-878e-6c8405433ac8" />

Why this happens I do not know, but doing that refresh is what fixes the seeking issue without any hassle

**Comment by jimdogx** [comment]
Great investigative work.  It might be worth mentioning to the server developers (sounds like they have two different code paths to accomplish the same thing).

I believe we can close this as it's not a client side issue, correct?

**Comment by Rand0mB0y** [comment]
> My previous deleted comment was actually a red herring.
> 
> I've gone even further. The behaviour of generating trickplay images, appears to have two different logics at play.
> 
> If you go into the "Scheduled Tasks" and generate trickplay images, it will use the folder name of the media. In the example path "/Big Hero 6/Big Hero 6 (2014) Blu-ray-2160p.mkv/" "Big Hero 6" will be the name of the trickplay, rather than "Big Hero 6 (2014) Blu-ray-2160p"
> 
> However, if you instead go to the individual movie, and refresh the metadata _AND_ the trickplay images, that will then be named "Big Hero 6 (2014) Blu-ray-2160p.trickplay

@RavingGrob 
That's interesting. I am also messing around with trickplays since you wrote your one to last comment. But, on my setup, I have different (buggy) behaviours 😂

- If I run a scheduled trickplay generation task, a trickplay folder with the name of the media is **correctly** being generated "Big Hero 6 (2014) Blu-ray-2160p.trickplay".
- If I run a "force metadata" trickplay rescan (like your screenshot).... nothing happens. No trickplays are being generated. I did try this with individual items only, though. I never tried a force rescan of an entire library, so maybe that would work.

Mind though, that: 

- I never name a file like "Big Hero 6 (2014) Blu-ray-2160p.mkv". My files would all be named like: "Big Hero 6 (2014) [Blu-ray-2160p].mkv". Usually, placing extra info in square brackets seems to avoid issues with Jellyfin, in my case... I bought the bullet a long time ago and renamed all my files that way. I even place the episode names of series in brackets. Technically, your renaming scheme is following the Jellyfin guidelines, but could the use of brackets fix the trickplay's folders names? How many other infos are after the year (e.g. "Big Hero 6 (2014) HEVC.h265.AAC.5.1.ENG.Multi.Blu-ray-2160p.mkv")?
- Also, Windows uses backslashes for file paths "\Big Hero 6\Big Hero 6 (2014) Blu-ray-2160p.mkv" while Linux and other OSs use forward slashes ""/Big Hero 6/Big Hero 6 (2014) Blu-ray-2160p.mkv". Recently, I had an issue of this nature for another Jellyfin project. Could this cause our different scheduled task behaviours?
  
Something else I read online since you posted about trickplays. Perhaps worth taking a look: 
1. [Older Roku devices seems to be preferring 5x5 trickplay images](https://github.com/jellyfin/jellyfin-roku/issues/14), rather than the stock 10x10 that Jellyfin creates. For this reason, even though, my device is relatively modern (Roku Express 4K), I'm regenerating my trickplay images in 5x5 size to see if that changes anything (it's taking a while).
2. [Roku seems to be generating its own trickplay images, internally, when transcoding](https://github.com/jellyfin/jellyfin-roku/issues/101#issuecomment-2531688154). This one is bizarre... because in our case the issue occurs indeed when we transcode. There can be instances in which [the two trickplays (Jellyfin and Roku) are both being displayed simultaneously](https://github.com/jellyfin/jellyfin-roku/issues/533#issuecomment-3288202032), for this reason there is a setting in the Roku client that tries to prevent that... mine is currently set to "disabled" I think. 
3. Perhaps this is irrelevant, but I found this issue [#538](https://github.com/jellyfin/jellyfin-roku/issues/538#event-3452767651) in which in an attempt to resolve the wrong ending time being displayed in the seek bar, the author removed some code relevant to the seek bar, literally claiming: [...I have no idea what the reason was for any of the code I removed, so I wouldn't be surprised if this breaks something else.](https://github.com/jellyfin/jellyfin-roku/issues/538#issuecomment-3336488989). Maybe something else, indeed, broke?

**Comment by Rand0mB0y** [comment]
> Great investigative work. It might be worth mentioning to the server developers (sounds like they have two different code paths to accomplish the same thing).
> 
> I believe we can close this as it's not a client side issue, correct?
  
@jimdogx Please don't close. Trickplays do not seem to affect my case, so far. And the behaviour of trickplay generation seems to vastly differ from @RavingGrob (please read my previous post). I, also, need more time (2-3 days) to generate new 5x5 files, but deleting trickplays and rescanning the library did not fix the issue, atm, so I'm not really holding my breath... I'll report though.

**Comment by RavingGrob** [comment]
> [@RavingGrob](https://github.com/RavingGrob) That's interesting. I am also messing around with trickplays since you wrote your one to last comment. But, on my setup, I have different (buggy) behaviours 😂
>     If I run a scheduled trickplay generation task, a trickplay folder with the name of the media is **correctly** being generated "Big Hero 6 (2014) Blu-ray-2160p.trickplay".
>     If I run a "force metadata" trickplay rescan (like your screenshot).... nothing happens. No trickplays are being generated. I did try this with individual items only, though. I never tried a force rescan of an entire library, so maybe that would work.

@Rand0mB0y  So, initially I also thought that nothing happened with the "replace metadata and existing trickplay images" method. I didn't see anything in the logs to indicate that something was happening from what I was looking at. But after a while, they showed up, properly named and seeking still working as expected. 

I'm doing a "scan library and replace trickplay images" now, and it *seems* to be doing the same behavior of the individual movie scan. I however can't test the seeking of them for a few hours.

EDIT: The folder naming behaviour actually might have come from something earlier than now.. I had assumed that "migrating" all trickplay data to the shared "trickplay" database and then deleting that would have wiped all trickplay files from my directories, but it seems that the ones that were named after the folder, persisted, and stuck around to prevent fresh trickplay images from generating, without explicitly replacing them. I am unaware of why or when this weird trickplay naming occurred.

This is a trickplay that's *still* here after so much rescanning and my latest request to refresh trickplay images.

<img width="878" height="823" alt="Image" src="https://github.com/user-attachments/assets/fcb501dd-8bec-44a5-bff0-30eb589e6350" />

**Comment by Rand0mB0y** [comment]
> ...it seems that the ones that were named after the folder, persisted, and stuck around to prevent fresh trickplay images from generating, without explicitly replacing them. I am unaware of why or when this weird trickplay naming occurred.
  
So, after days of re-generating trickplay images... things are still a mess here. I have reasons to agree with @RavingGrob  that, indeed, trickplay has something to do with the broken seek bar when transcoding. Although, in my case, some files got fixed, others didn't. But after analysing the SQL database, I can clearly see that there are issues with JF's trickplay in general... at least in my system.
  
1. **Jellyfin trickplay feature seems to be half broken**:
   - After regenerating everything in 5x5, many 10x10 folders persistently remained... now attempting to re-regenerate again
   - Some new trickplay images, instead, were correctly generated, but with issues in the SQL database. In the db, some of the ItemIds did not get updated with the new 5x5 fields and wrongly still report the old 10 TitleWidth and 10 TitleHeigh. Basically [this happened](https://github.com/jellyfin/jellyfin/issues/12887#issuecomment-2448468558).

2. **Moonfin for Roku can seek**:
   - I installed it just to test this, and the seek bar seems to be working fine when transcoding the same "problematic" files
   - The interface is overall a bit new and buggy, but the trickplay images are (mostly) working, too

3. **Why modifying the name of the video folder and rescanning fixes seek in my case:**
   - In the BaseItems table of SQL, there is an ItemId value which is latched to the actual file name of the video. The same ItemId is associated with the trickplay image details of the video in the TrickplayInfos table. When renaming a video file, the raw related to its trickplay gets deleted. Now JF believes the file has no trickplay images, and Roku can seek perfectly while transcoding, but (of course) you won't see trickplay images while seeking. This process "fixes" seeking, in my case, because of deleting a raw containing wrongly generated trickplay metadata.

        @RavingGrob you could attempt deleting the raw in the TrickplayInfos table that is relevant to a file that does not seek, and see if that fixes yours too. Or, at least, you could check if that raw contains wrong trickplay info... particularly for those persistent folders you seem to have, too.

**Comment by RavingGrob** [comment]
> [@RavingGrob](https://github.com/RavingGrob) you could attempt deleting the raw in the TrickplayInfos table that is relevant to a file that does not seek, and see if that fixes yours too. Or, at least, you could check if that raw contains wrong trickplay info... particularly for those persistent folders you seem to have, too.

@Rand0mB0y So, based on everything I've tested, the replace metadata and trickplay images from the library view, worked for all my media.. I haven't done as thorough as testing as I want, as I've been busy with work.

One thing that is interesting, that I don't believe *ever* worked, even before I nuked the jellyfin DB the first time, is the trickplay images. However, after getting all this mess sorted out, I'm seeing trickplay in the official Roku app when seeking now.

I haven't really tested which media have trickplay images showing properly, so there might still be something else involved blocking that, if they don't all display.

Funny thing about it though, is all my trickplays are generated 10x10, and aren't *seemingly* stopping anything with the Roku stick I have at least.


Do you store the trickplays with the media, or in a trickplay db like I believe the default is?

**Comment by Rand0mB0y** [comment]
> [@Rand0mB0y](https://github.com/Rand0mB0y) So, based on everything I've tested, the replace metadata and trickplay images from the library view, worked for all my media.. I haven't done as thorough as testing as I want, as I've been busy with work.

@RavingGrob I am so happy for you that this is sorted! I know how painful this all is!

> Funny thing about it though, is all my trickplays are generated 10x10, and aren't _seemingly_ stopping anything with the Roku stick I have at least.

Yeah, I don't think the 5x5 format is necessary for newer devices. As I was going through the hassle of regenerating the trickplays, I thought I'd do it in a more Roku-friendly format.... little I knew that this was going to mess with my db.

> Do you store the trickplays with the media, or in a trickplay db like I believe the default is?

Mine are stored in the media folders.

@RavingGrob Do the Roku's stock trickplay show instead of the Jellyfin when transcoding? Roku's original TP are way bigger than the Jellyfin's. After regenerating the trickplays, I can finally see the Roku "originals" when transcoding:


<img width="911" height="1103" alt="Image" src="https://github.com/user-attachments/assets/c4d01d7f-169a-491b-bad3-1f9a8a8d2e30" />

**Comment by RavingGrob** [comment]
> 
> [@RavingGrob](https://github.com/RavingGrob) Do the Roku's stock trickplay show instead of the Jellyfin when transcoding? Roku's original TP are way bigger than the Jellyfin's. After regenerating the trickplays, I can finally see the Roku "originals" when transcoding

So I've finally had some time to sit down and test.

Transcoding media needs "Custom Trickplay" enabled for them show up, direct play does not, but also is not negatively affected by "Custom Trickplay.

I have never seen the larger style trickplay images in that second screenshot. I presume that's a limitation of the 10x10 vs 5x5 scheme, but if all I have to do is enable the "Custom Trickplay" feature, then I'm fine personally.

**Comment by RazorzMcLazorz** [comment]
Okay so i read through this all, and i tried regenerating the trickplay, and enabling the "Custom Trickplay" does not help with it. Also i do have my trickplay images set to generate as 16:9 320px width. Now i am running jellyfin server version 10.11.5  and thats because after i upgraded last, i broke all user information in the migration, so im afraid to update again, once i get a moment i will try updating jellyfin again

I should probably add, im running jellyfin off of truenas if that matters.

So in short my server and anyone using Roku Devices on it so far cant skip ahead, or if they are ahead of the first minute, it will push them back to the first minute regardless while the movie is transcoded.

**Comment by Rand0mB0y** [comment]
> Okay so i read through this all, and i tried regenerating the trickplay, and enabling the "Custom Trickplay" does not help with it. Also i do have my trickplay images set to generate as 16:9 320px width. 
  
@RazorzMcLazorz 
I have spent an incredible amount of time trying to sort this out. In the end I moved to Nvidia Shield for this very reason. Although my problems with skipping are over, this sucked, because the Roku Jellyfin team here on Github is probably the most friendly and helpful team among other official Jellyfin teams. I even thought about keeping the Roku just to keep testing it out every once in a while and see what's up with the Roku app/team, but this ad-junky Roku OS is too much of a pain. Atm I still have the Roku 4k Express around. Is yours the same model? 

>I should probably add, im running jellyfin off of truenas if that matters.

My server runs on Windows bare metal, but I'm migrating to Proxmox and JF will run soon on a Debian LXC. I may test this all out again once the migration is completed. 

> Now i am running jellyfin server version 10.11.5 and thats because after i upgraded last, i broke all user information in the migration, so im afraid to update again, once i get a moment i will try updating jellyfin again

JF 10.11.6 has a major issue with directors and writers metadata not being pulled, so I'd skip it. Also, JF 10.11.7 just came out. 

> So in short my server and anyone using Roku Devices on it so far cant skip ahead, or if they are ahead of the first minute, it will push them back to the first minute regardless while the movie is transcoded.

Sadly that was exactly the case for me, too. If I remember correctly, Moonfin could skip ahead fine though... it wasn't a super pretty client and had other issues, but it just came out by then, so you could give it a shot and maybe now it's better?

**Comment by jimdogx** [comment]
I'd be curious to see if the next release has any affect because it will have a completely new / redesigned seek bar: https://github.com/jellyfin/jellyfin-roku/pull/786

**Comment by RazorzMcLazorz** [comment]
@Rand0mB0y I do run Roku 4k express as well, although the other family that use my jellyfin server don't, I don't actually know which model they are using.

Thanks I should of looked into the patches I didn't realize the next version is bugged, and since the latest is super new it's best to wait for more updates

I've never heard of moonfin I'll take a look at it, I'll definately give it a try, although if moonfin works what's different in the code between that and jellyfin-Roku

This sounds like a fun rabbit hole that I might look down

**Comment by RazorzMcLazorz** [comment]
> I'd be curious to see if the next release has any affect because it will have a completely new / redesigned seek bar: https://github.com/jellyfin/jellyfin-roku/pull/786

Oh yeah I would also like to know, 🤞 hopefully it works but if moonfin source code is available I think I'll compare it against jellyfin-Roku and see if I can find anything related to it
